name: Update Lambda Functions

on:
  workflow_dispatch:
    inputs:
      function_name:
        description: "Lambda function to deploy (e.g., g2_handler, gamil_extractor, or all)"
        required: true
        default: "all"

# env:
#   AWS_REGION: ap-southeast-2 # Your preferred AWS region

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Deploy Lambda Functions
      run: |
        case "${{ github.event.inputs.function_name }}" in
          g2_handler)
            echo "Deploying g2_handler..."
            cd extract/g2_handler
            mkdir -p package
            pip install -r requirements.txt -t package/
            cp lambda_function.py package/
            zip -r lambda_function.zip package/
            aws lambda update-function-code \
              --function-name g2_handler \
              --zip-file fileb://lambda_function.zip
            ;;
          gamil_extractor)
            echo "Deploying gamil_extractor..."
            cd extract/gamil_extractor
            mkdir -p package
            pip install -r requirements.txt -t package/
            cp lambda_function.py package/
            zip -r lambda_function.zip package/
            aws lambda update-function-code \
              --function-name gamil_extractor \
              --zip-file fileb://lambda_function.zip
            ;;
          all)
            echo "Deploying all Lambda functions..."
            # Deploy g2_handler
            cd extract/g2_handler
            mkdir -p package
            pip install -r requirements.txt -t package/
            cp lambda_function.py package/
            zip -r lambda_function.zip package/
            aws lambda update-function-code \
              --function-name g2_handler \
              --zip-file fileb://lambda_function.zip
            cd ../..

            # Deploy gamil_extractor
            cd extract/gamil_extractor
            mkdir -p package
            pip install -r requirements.txt -t package/
            cp lambda_function.py package/
            zip -r lambda_function.zip package/
            aws lambda update-function-code \
              --function-name gamil_extractor \
              --zip-file fileb://lambda_function.zip
            ;;
          *)
            echo "Invalid option provided: ${{ github.event.inputs.function_name }}"
            exit 1
            ;;
        esac
