name: Deploy Lambda Function

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: g2 handler
      run: |
        cd extract/g2_handler
        pip install -r requirements.txt -t package/
        mv lambda_function.py package/
        zip -r lambda_function.zip package/

    - name: gamil_extractor
      run: |
        cd extract/gamil_extractor
        pip install -r requirements.txt -t package/
        mv lambda_function.py package/
        zip -r lambda_function.zip package/

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      working-directory: terraform
      run: |
        terraform apply -auto-approve
